name: FastAPI Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Set the registry URL as an environment variable
  REGISTRY: docker.io
  # Set the image name as an environment variable
  IMAGE_NAME: sample-fast-api
  IMAGE_TAG: ${{ github.sha }}
  # IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step prints "Hello World" to the console
      - run: echo "Hello World"

      # This step checks out the repository using the actions/checkout@v4.2.2 action
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # This step lists all files in the repository and prints them to the console
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker Image and Push to the Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: docker.io/ha20003660/sample-fast-api:$IMAGE_TAG
          # tags: $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG , $REGISTRY/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
