name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at evert 5th minute of every hour
    - cron: "5 * * * *"

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      # This step prints "Hello World" to the console
      - run: echo "Hello World"

      # This step checks out the repository using the actions/checkout@v4.2.2 action
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # This step lists all files in the repository and prints them to the console
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
